name: Release

on:
  push:
    tags:
      - "*"
    branches:
      - 'workflows' # useful for testing

env:
  ghcr_latest_tag: "${{ github.ref_type == 'tag' && ',ghcr.io/vshn/ldaplogin:latest' || '' }}"

jobs:
  dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker build
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: "ghcr.io/vshn/ldaplogin:${{ github.ref_name }}${{ env.ghcr_latest_tag }}"
